package com.weatherhub.operations;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.weatherhub.camera.CameraAlert; import com.weatherhub.camera.CameraAlertMapper; import com.weatherhub.common.BusinessException; import com.weatherhub.officialalert.OfficialAlertService; import com.weatherhub.operations.dto.*; import com.weatherhub.rbac.MenuMapper; import com.weatherhub.tropical.TropicalCycloneService; import com.weatherhub.user.User; import com.weatherhub.user.UserMapper; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.time.OffsetDateTime; import java.util.List; import java.util.Collections;
@Service @RequiredArgsConstructor public class OperationsService {
 private final OpsEventMapper eventMapper; private final OpsWorkOrderMapper orderMapper; private final OpsNotificationMapper notificationMapper; private final OpsWorkOrderCollaboratorMapper collaboratorMapper; private final OpsWorkOrderProgressMapper progressMapper; private final UserMapper userMapper; private final CameraAlertMapper cameraAlertMapper; private final OfficialAlertService officialAlertService; private final TropicalCycloneService tropicalCycloneService; private final MenuMapper menuMapper;
 public List<OpsEventVO> events(String status,String sourceType){syncCameraAlerts();return eventMapper.selectList(new LambdaQueryWrapper<OpsEvent>().eq(status!=null&&!status.isBlank(),OpsEvent::getStatus,status).eq(sourceType!=null&&!sourceType.isBlank(),OpsEvent::getSourceType,sourceType).orderByDesc(OpsEvent::getOccurredAt)).stream().map(OpsEventVO::from).toList();}
 @Transactional public void syncExternalEvents(){syncCameraAlerts();syncOfficialAlerts();syncTropicalCyclones();}
 @Transactional public OpsEventVO createEvent(SaveEventRequest r,Long actor){if(!"MANUAL".equals(r.sourceType()))throw new BusinessException("Only manually reported events can be registered");OpsEvent e=new OpsEvent();e.setSourceType(r.sourceType());e.setSourceKey(blank(r.sourceKey()));e.setLevel(defaulted(r.level(),"YELLOW"));e.setStatus("OPEN");e.setTitle(r.title().trim());e.setContent(blank(r.content()));e.setRegionName(blank(r.regionName()));e.setLongitude(r.longitude());e.setLatitude(r.latitude());e.setOccurredAt(r.occurredAt()==null?LocalDateTime.now():r.occurredAt());e.setCreatedBy(actor);eventMapper.insert(e);notifyUser(actor,"EVENT","新事件："+e.getTitle(),e.getContent(),"EVENT",e.getId());return OpsEventVO.from(e);}
 public List<OpsWorkOrderVO> workOrders(String status){return orderMapper.selectList(new LambdaQueryWrapper<OpsWorkOrder>().eq(status!=null&&!status.isBlank(),OpsWorkOrder::getStatus,status).orderByDesc(OpsWorkOrder::getCreatedAt)).stream().map(this::toWorkOrder).toList();}
 @Transactional public OpsWorkOrderVO createWorkOrder(SaveWorkOrderRequest r,Long actor){OpsEvent e=requireEvent(r.eventId());if(r.assigneeId()!=null)requireUser(r.assigneeId());OpsWorkOrder w=new OpsWorkOrder();w.setEventId(e.getId());w.setTitle(r.title().trim());w.setDescription(blank(r.description()));w.setPriority(defaulted(r.priority(),e.getLevel()));w.setStatus("TODO");w.setAssigneeId(r.assigneeId());w.setCreatedBy(actor);w.setDueAt(r.dueAt());orderMapper.insert(w);if(w.getAssigneeId()!=null)notifyUser(w.getAssigneeId(),"WORK_ORDER","待处理工单："+w.getTitle(),"关联事件："+e.getTitle(),"WORK_ORDER",w.getId());return toWorkOrder(w);}
 @Transactional public OpsWorkOrderVO updateWorkOrderStatus(Long id,UpdateWorkOrderStatusRequest r,Long actor){OpsWorkOrder w=requireOrder(id);w.setStatus(r.status());w.setCompletedAt("DONE".equals(r.status())?LocalDateTime.now():null);orderMapper.updateById(w);if(!actor.equals(w.getCreatedBy()))notifyUser(w.getCreatedBy(),"WORK_ORDER","工单状态更新："+w.getTitle(),statusText(w.getStatus()),"WORK_ORDER",w.getId());return toWorkOrder(w);}
 @Transactional public OpsWorkOrderVO assignWorkOrder(Long id,AssignWorkOrderRequest r,Long actor){OpsWorkOrder w=requireOrder(id);requireUser(r.assigneeId());if(r.assigneeId().equals(actor))throw new BusinessException("管理员不能指派自己");Long previous=w.getAssigneeId();w.setAssigneeId(r.assigneeId());w.setStatus("TODO");orderMapper.updateById(w);if(previous!=null&&!previous.equals(r.assigneeId()))notifyUser(previous,"WORK_ORDER","工单已移交："+w.getTitle(),"管理员已重新指派负责人","WORK_ORDER",id);notifyUser(r.assigneeId(),"WORK_ORDER","已指派工单："+w.getTitle(),"请及时处理并反馈进展","WORK_ORDER",id);return toWorkOrder(w);}
 public WorkOrderDetailVO workOrderDetail(Long id){OpsWorkOrder w=requireOrder(id);return new WorkOrderDetailVO(toWorkOrder(w),progress(id));}
 @Transactional public WorkOrderProgressVO addProgress(Long id,AddWorkOrderProgressRequest r,Long actor){OpsWorkOrder w=requireOrder(id);if(!actor.equals(w.getAssigneeId()))throw new BusinessException("仅负责人可以填写处置进展");String target=blank(r.statusAfter());if(target!=null&&!target.equals("PROCESSING")&&!target.equals("PENDING_ACCEPTANCE"))throw new BusinessException("负责人只能开始处置或申请验收");OpsWorkOrderProgress p=new OpsWorkOrderProgress();p.setWorkOrderId(id);p.setContent(r.content().trim());p.setLongitude(r.longitude());p.setLatitude(r.latitude());p.setStatusAfter(target);p.setCreatedBy(actor);progressMapper.insert(p);if(target!=null){w.setStatus(target);orderMapper.updateById(w);}notifyUser(w.getCreatedBy(),"WORK_ORDER",target!=null&&target.equals("PENDING_ACCEPTANCE")?"工单待验收："+w.getTitle():"工单进展更新："+w.getTitle(),p.getContent(),"WORK_ORDER",id);return progressVO(p);}
 @Transactional public OpsWorkOrderVO acceptWorkOrder(Long id,AcceptWorkOrderRequest r,Long actor){OpsWorkOrder w=requireOrder(id);if(!"PENDING_ACCEPTANCE".equals(w.getStatus()))throw new BusinessException("当前工单不在待验收状态");w.setStatus(r.approved()?"DONE":"PROCESSING");w.setCompletedAt(r.approved()?LocalDateTime.now():null);orderMapper.updateById(w);OpsWorkOrderProgress p=new OpsWorkOrderProgress();p.setWorkOrderId(id);p.setContent(r.comment().trim());p.setStatusAfter(w.getStatus());p.setCreatedBy(actor);progressMapper.insert(p);notifyUser(w.getAssigneeId(),"WORK_ORDER",r.approved()?"工单验收通过："+w.getTitle():"工单验收退回："+w.getTitle(),p.getContent(),"WORK_ORDER",id);return toWorkOrder(w);}
 @Transactional public void deleteWorkOrder(Long id){requireOrder(id);notificationMapper.delete(new LambdaQueryWrapper<OpsNotification>().eq(OpsNotification::getTargetType,"WORK_ORDER").eq(OpsNotification::getTargetId,id));collaboratorMapper.delete(new LambdaQueryWrapper<OpsWorkOrderCollaborator>().eq(OpsWorkOrderCollaborator::getWorkOrderId,id));progressMapper.delete(new LambdaQueryWrapper<OpsWorkOrderProgress>().eq(OpsWorkOrderProgress::getWorkOrderId,id));orderMapper.deleteById(id);}
 public List<OpsNotificationVO> notifications(Long user){return notificationMapper.selectList(new LambdaQueryWrapper<OpsNotification>().eq(OpsNotification::getUserId,user).orderByAsc(OpsNotification::getReadAt).orderByDesc(OpsNotification::getCreatedAt).last("LIMIT 50")).stream().map(OpsNotificationVO::from).toList();}
 @Transactional public void readNotification(Long id,Long user){OpsNotification n=notificationMapper.selectById(id);if(n==null||!user.equals(n.getUserId()))throw new BusinessException(404,"通知不存在");if(n.getReadAt()==null){n.setReadAt(LocalDateTime.now());notificationMapper.updateById(n);}}
 private OpsWorkOrderVO toWorkOrder(OpsWorkOrder w){OpsEvent e=eventMapper.selectById(w.getEventId());User a=w.getAssigneeId()==null?null:userMapper.selectById(w.getAssigneeId());return OpsWorkOrderVO.from(w,e==null?"已删除事件":e.getTitle(),a==null?null:a.getNickname());}
 private List<WorkOrderProgressVO> progress(Long id){return progressMapper.selectList(new LambdaQueryWrapper<OpsWorkOrderProgress>().eq(OpsWorkOrderProgress::getWorkOrderId,id).orderByAsc(OpsWorkOrderProgress::getCreatedAt)).stream().map(this::progressVO).toList();}
 private WorkOrderProgressVO progressVO(OpsWorkOrderProgress p){User u=userMapper.selectById(p.getCreatedBy());return new WorkOrderProgressVO(p.getId(),p.getContent(),List.of(),p.getLongitude(),p.getLatitude(),p.getStatusAfter(),p.getCreatedBy(),u==null?"已删除用户":u.getNickname(),p.getCreatedAt());}
 private void syncCameraAlerts(){for(CameraAlert alert:cameraAlertMapper.selectList(new LambdaQueryWrapper<CameraAlert>().eq(CameraAlert::getStatus,"ACTIVE"))){String key="camera:"+alert.getId();if(eventMapper.selectCount(new LambdaQueryWrapper<OpsEvent>().eq(OpsEvent::getSourceType,"CAMERA_ALERT").eq(OpsEvent::getSourceKey,key))>0)continue;OpsEvent e=new OpsEvent();e.setSourceType("CAMERA_ALERT");e.setSourceKey(key);e.setLevel(alert.getLevel());e.setStatus("OPEN");e.setTitle(alert.getTitle());e.setContent(alert.getContent());e.setOccurredAt(alert.getLastDetectedAt());e.setCreatedBy(0L);eventMapper.insert(e);}}
 private void syncOfficialAlerts(){var overview=officialAlertService.overview();if(!overview.configured())return;for(var region:overview.regions())for(var warning:region.warnings()){String key=warning.id().isBlank()?region.locationId()+":"+warning.title()+":"+warning.pubTime():warning.id();upsertExternal("OFFICIAL_ALERT",key,normalizeLevel(warning.level()),warning.title(),warning.text(),region.regionName(),null,null,timeOrNow(warning.pubTime()));}}
 private void syncTropicalCyclones(){var overview=tropicalCycloneService.overview();if(!overview.configured())return;for(var storm:overview.storms()){String content="类型："+storm.type()+"；中心气压："+storm.pressure()+" hPa；最大风速："+storm.windSpeed();upsertExternal("TROPICAL_CYCLONE",storm.id(),"YELLOW","活跃台风："+storm.name(),content,"西北太平洋",number(storm.lon()),number(storm.lat()),LocalDateTime.now());}}
 private void upsertExternal(String type,String key,String level,String title,String content,String region,Double longitude,Double latitude,LocalDateTime occurredAt){OpsEvent event=eventMapper.selectOne(new LambdaQueryWrapper<OpsEvent>().eq(OpsEvent::getSourceType,type).eq(OpsEvent::getSourceKey,key).last("LIMIT 1"));boolean created=event==null;if(created){event=new OpsEvent();event.setSourceType(type);event.setSourceKey(key);event.setCreatedBy(0L);}event.setLevel(level);event.setStatus("OPEN");event.setTitle(title.isBlank()?type:title);event.setContent(blank(content));event.setRegionName(blank(region));event.setLongitude(longitude);event.setLatitude(latitude);event.setOccurredAt(occurredAt);if(created){eventMapper.insert(event);notifyEventReaders(event);}else eventMapper.updateById(event);}
 private static String normalizeLevel(String level){if(level==null)return "YELLOW";String v=level.trim();if(v.matches("(?i).*red.*")||v.contains("红"))return "RED";if(v.matches("(?i).*orange.*")||v.contains("橙"))return "ORANGE";if(v.matches("(?i).*blue.*")||v.contains("蓝"))return "BLUE";return "YELLOW";} private static LocalDateTime timeOrNow(String value){try{return OffsetDateTime.parse(value).toLocalDateTime();}catch(Exception ignored){return LocalDateTime.now();}} private static Double number(String value){try{return Double.valueOf(value);}catch(Exception ignored){return null;}}
 private void notifyUser(Long user,String type,String title,String content,String targetType,Long target){OpsNotification n=new OpsNotification();n.setUserId(user);n.setType(type);n.setTitle(title);n.setContent(blank(content));n.setTargetType(targetType);n.setTargetId(target);notificationMapper.insert(n);}
 private void notifyEventReaders(OpsEvent event){for(Long userId:menuMapper.selectUserIdsByPermission("ops:event:read")){notifyUser(userId,"EVENT","新预警事件："+event.getTitle(),event.getContent(),"EVENT",event.getId());}}
 private OpsEvent requireEvent(Long id){OpsEvent e=eventMapper.selectById(id);if(e==null)throw new BusinessException(404,"事件不存在");return e;} private OpsWorkOrder requireOrder(Long id){OpsWorkOrder w=orderMapper.selectById(id);if(w==null)throw new BusinessException(404,"工单不存在");return w;} private User requireUser(Long id){User u=userMapper.selectById(id);if(u==null)throw new BusinessException(404,"处理人不存在");return u;} private static String blank(String v){return v==null||v.isBlank()?null:v.trim();} private static String defaulted(String v,String f){return v==null||v.isBlank()?f:v.trim();} private static String statusText(String s){return switch(s){case "TODO"->"待处理";case "PROCESSING"->"处理中";default->"已完成";};}
}
