apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
  namespace: weather
data:
  TZ: Asia/Shanghai
  MYSQL_DATABASE: weatherhub
  MYSQL_URL: jdbc:mysql://mysql:3306/weatherhub?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  MYSQL_USERNAME: root
  JWT_EXPIRE_HOURS: "24"
  SEED_RBAC: "true"
  CORS_ORIGINS: http://localhost,http://127.0.0.1,https://quinn761.github.io,http://60.205.211.104,http://60.205.211.104:30000,http://60.205.211.104:30080
  POSTGIS_DATABASE: weatherhub_gis
  POSTGIS_USERNAME: weatherhub
  POSTGIS_URL: jdbc:postgresql://postgis:5432/weatherhub_gis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  AI_BASE_URL: "https://api.deepseek.com"
  AI_MODEL: "deepseek-chat"
---
apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
  namespace: weather
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: WeatherHub2026Mysql
  JWT_SECRET: WeatherHubJwtSecret2026ChangeMeToLongRandomString
  POSTGIS_PASSWORD: WeatherHub2026Postgis
  AI_API_KEY: ""
